README.md
license

Fix license text

---

README.md

Add note about parameters in source strings

---

pt-br/1/00-overview.md
pt-br/1/arrays.md
pt-br/1/arraysstructs2.md
pt-br/1/contracts.md
pt-br/1/datatypes.md
pt-br/1/events.md
pt-br/1/functions.md
pt-br/1/functions2.md
pt-br/1/functions3.md
pt-br/1/keccak256.md
pt-br/1/lessoncomplete.md
pt-br/1/lessonoverview.md
pt-br/1/math.md
pt-br/1/puttingittogether.md
pt-br/1/structs.md
pt-br/1/web3js.md
pt-br/index.json
pt-br/index.ts
pt-br/share-template-msgs.json

* MD files translated
* Config files translated

WIP Lesson 1 translated to PT-BR

---

pt/1/00-overview.md
pt/1/arraysstructs2.md

Fixes on lesson titles

---

en/lander.yml

- [X ] I didn't use a machine to do these translations
- [X ] I assign all copyright to Loom Network for these translations

add lander in english

---

pt/1/00-overview.md
pt/1/arrays.md
pt/1/arraysstructs2.md
pt/1/contracts.md
pt/1/datatypes.md
pt/1/events.md
pt/1/functions.md
pt/1/functions2.md
pt/1/functions3.md
pt/1/keccak256.md
pt/1/lessonoverview.md
pt/1/math.md
pt/1/structs.md
pt/1/web3js.md
pt/2/1-overview.md
pt/2/12-multiplereturns.md
pt/2/13-kittygenes.md
pt/2/14-wrappingitup.md
pt/2/2-mappings.md
pt/2/3-msgsender.md
pt/2/4-require.md
pt/2/5-inheritance.md
pt/2/7-storage.md
pt/2/8-feedandmultiply2.md
pt/index.json
pt/share-template-msgs.json

I'd like to say thanks to thanks to github.com/joscaohenri, which helped with the spell checking

Many PT fixes

---

pt/lander.yml

Landing page in pt

---

zh/2/3-msgsender.md

Fix answer code in Chinese L2 Ch3

---

en/4/battle-02.md
en/4/withdraw.md

Minor lesson fixes

---

en/4/battle-04.md

Fixed typo

---

en/4/payable.md

Fix a couple of typos in L4Ch1

---

en/4/battle-02.md

another typo fix - "random number between 0 and 99"

---

en/4/battle-06.md

small typo- "random number between 0 and 99"

---

en/4/00-overview.md

Fix color of payable keyword in L4 overview

---

ko/index.ts

Enable Korean Lesson 2

---

pl/index.json
pl/index.ts
pl/lander.yml

I prepare first pars of polish translation. I am going to tranlate whole project in few next PR
BTW (I am programmer for years, but it is my first open-source contribution)

translate index.json and lander into polish

---

en/lander.yml

…el of es directory.
- [ x ] I did these translations myself and own copyright for them
- [ x ] I didn't use a machine to do these translations
- [ x ] I assign all copyright to Loom Network for these translations

fix grammatical error

---

en/2/7-storage.md

Add missing word

---

es/2/1-overview.md
es/2/10-interactingcontracts.md
es/2/11-interactingcontracts2.md
es/2/12-multiplereturns.md
es/2/14-wrappingitup.md
es/2/3-msgsender.md
es/2/7-storage.md
es/2/8-feedandmultiply2.md

- [ x ] I did these translations myself and own copyright for them
- [ x ] I didn't use a machine to do these translations
- [ x ] I assign all copyright to Loom Network for these translations

[ES] Lesson 2 translations

---

pt/4/00-overview.md
pt/4/battle-01.md
pt/4/battle-02.md
pt/4/battle-03.md
pt/4/battle-04.md
pt/4/battle-05.md
pt/4/battle-06.md
pt/4/battle-07.md
pt/4/battle-08.md
pt/4/battle-09.md
pt/4/lessoncomplete.md
pt/4/payable.md
pt/4/withdraw.md
pt/4/wrappingitup.md
pt/index.json
pt/index.ts
pt/share-template-msgs.json

Translations for lesson 4 pt br

---

es/3/00-overview.md
es/3/01-externaldependencies.md
es/3/02-ownable.md
es/3/03-onlyowner.md
es/3/04-gas.md
es/3/05-timeunits.md
es/3/06-zombiecooldowns.md
es/3/07-zombiecooldowns2.md
es/3/08-functionmodifiers.md
es/3/09-zombiemodifiers.md
es/3/10-savinggasview.md
es/3/11-savinggasstorage.md
es/3/12-forloops.md
es/3/13-wrappingitup.md
es/3/14-lessoncomplete.md

- [ x ] I did these translations myself and own copyright for them
- [ x ] I didn't use a machine to do these translations
- [ x ] I assign all copyright to Loom Network for these translations

Lesson 3 translation completed

---

en/4/battle-02.md

Add omitted 'of' in the sentence

---

pt/index.json

Fixed index.json lesson 4 config

---

jp/4/battle-02.md
jp/4/battle-03.md
jp/4/battle-04.md
jp/4/battle-05.md
jp/4/battle-06.md
jp/4/battle-07.md
jp/4/battle-08.md
jp/4/battle-09.md
jp/4/payable.md
jp/4/withdraw.md
jp/index.ts
ko/index.ts

Fix JP L4 & enable KO L4

---

jp/3/09-zombiemodifiers.md

Modified a couple of mistranslations

---

ru/index.ts

Enable Russian L3

---

zh/2/13-kittygenes.md

fixed a typo in anwser in l2ch13 of Chinese

---

fr/3/10-savinggasview.md
fr/3/12-forloops.md

fix smalls typos on two french translations files

fix smalls typos on two french translations files

---

en/4/battle-05.md
en/4/battle-06.md
en/4/battle-07.md
en/4/battle-08.md
en/4/battle-09.md

Fixing a couple mistakes in the lesson code

Fixing errors in lesson 4

---

en/2/11-interactingcontracts2.md

Add missing semicolon to numberContract.
- [x ] I didn't use a machine to do these translations
- [x ] I assign all copyright to Loom Network for these translations

Add missing semicolon to numberContract

---

zh/3/01-externaldependencies.md
zh/3/02-ownable.md
zh/3/03-onlyowner.md
zh/3/05-timeunits.md
zh/3/06-zombiecooldowns.md
zh/3/07-zombiecooldowns2.md
zh/3/08-functionmodifiers.md
zh/3/09-zombiemodifiers.md
zh/3/10-savinggasview.md
zh/3/11-savinggasstorage.md
zh/3/12-forloops.md
zh/4/battle-02.md
zh/4/battle-03.md
zh/4/battle-04.md
zh/4/battle-05.md
zh/4/battle-06.md
zh/4/battle-07.md
zh/4/battle-08.md
zh/4/battle-09.md
zh/4/payable.md
zh/4/withdraw.md

- [ ✓] I did these translations myself and own copyright for them
- [✓ ] I didn't use a machine to do these translations
- [✓ ] I assign all copyright to Loom Network for these translations

lesson3 and lesson4 fix

---

en/4/battle-06.md

user reported a bug, when starting code for L4 Ch8 was with pragma, but answer checker was not accepting correct answer that defines pragma

missing pragma solidity in answer checker

---

en/4/battle-02.md
en/4/battle-03.md
en/4/battle-08.md
en/4/battle-09.md

more missing pragma added

---

es/3/07-zombiecooldowns2.md

- [ x ] I did these translations myself and own copyright for them
- [ x ] I didn't use a machine to do these translations
- [ x ] I assign all copyright to Loom Network for these translations

Lesson 3 Fixing Gramatical Errors

---

en/5/13-comments.md

Small language fix for 5/13

---

en/4/battle-05.md

It seems to me that the answer should include this function as it was in the code at the start of the lesson.
I will add the fix to the other languages once confirmed that this is the real answer

Answer is missing a function

---

en/3/08-functionmodifiers.md
en/5/11-safemath-3.md
en/5/12-safemath-4.md
en/5/13-comments.md

Quick fixes

---

fr/index.json

 Translation fr - Lesson 4 - update fr/index.json

---

zh/index.json

add lesson 5 share content in index.json

---

zh/2/13-kittygenes.md

Fix answer: wrong parameter name.

---

en/3/02-ownable.md

The lesson 4 already released, then the sentense are no more sense.

EN - Chapter: 3 Lesson:002

---

pt/5/00-overview.md
pt/5/01-erc721-1.md
pt/5/02-erc721-2.md
pt/5/03-erc721-3.md
pt/5/04-erc721-4.md
pt/5/05-erc721-5.md
pt/5/06-erc721-6.md
pt/5/07-erc721-7.md
pt/5/08-erc721-8.md
pt/5/09-safemath-1.md
pt/5/10-safemath-2.md
pt/5/11-safemath-3.md
pt/5/12-safemath-4.md
pt/5/13-comments.md
pt/5/14-wrappingitup.md
pt/5/15-lessoncomplete.md
pt/index.json
pt/index.ts
pt/share-template-msgs.json

LESSON - 5 PT

---

zh/index.ts
zh/lander.yml

also update index.ts in Chinese version

---

ru/4/00-overview.md

Fix roadmap image in RU L4

---

zh/3/00-overview.md
zh/4/00-overview.md
zh/4/battle-02.md
zh/4/battle-05.md
zh/4/battle-09.md
zh/5/00-overview.md
zh/5/01-erc721-1.md
zh/5/10-safemath-2.md
zh/5/12-safemath-4.md
zh/5/13-comments.md

fixed some bugs in Chinese version

---

jp/4/battle-02.md
jp/5/13-comments.md
jp/index.json

Mami m l5 fixtext

---

en/1/functions2.md
es/1/functions2.md
fr/1/functions2.md
jp/1/functions2.md
ko/1/functions2.md
no/1/functions2.md
pl/1/functions2.md
pt/1/functions2.md
ru/1/functions2.md
th/1/functions2.md
tr/1/functions2.md
zh/1/functions2.md

Fix invalid brace.

---

en/6/00-overview.md
en/6/01.md
en/6/02.md
en/6/03.md
en/6/04.md
en/6/05.md
en/6/06.md
en/6/07.md
en/6/08.md
en/6/09.md
en/6/10-wrappingitup.md
en/6/lessoncomplete.md
en/index.json
en/index.ts
en/share-template-msgs.json

add lesson 6

---

en/3/12-forloops.md
es/3/12-forloops.md
fr/3/12-forloops.md
jp/3/12-forloops.md
ko/3/12-forloops.md
no/3/12-forloops.md
pt/3/12-forloops.md
ru/3/12-forloops.md
th/3/12-forloops.md
zh/3/12-forloops.md

Lesson3, Chapter 12. Fixed spacing in mapping declaration.

---

en/5/12-safemath-4.md
en/5/13-comments.md

Lesson 5 - chapter 12 & 13 forgets SafeMath libraries and code changes done in previous chapters.

SafeMath forgotten for uint32/uint16 in chapter 12-13

---

pt/6/00-overview.md
pt/6/01-intro-web3.md
pt/6/02-web3-providers.md
pt/6/03-talking-to-contracts.md
pt/6/04-calling-contract-functions.md
pt/6/05-metamask-accounts.md
pt/6/06-displaying-zombie-army.md
pt/6/07-sending-transactions.md
pt/6/08-calling-payable-functions.md
pt/6/09-subscribing-to-events.md
pt/6/10-wrappingitup.md
pt/6/lessoncomplete.md
pt/index.json
pt/index.ts
pt/share-template-msgs.json

LESSON - 6 PT

---

jp/index.json

Links to jp twitter account are wrong!

Fix jp twitter account

---

en/6/03.md
es/6/03.md
fr/6/03.md
jp/6/03.md
pt/6/03-talking-to-contracts.md
zh/6/03.md

lesson6 Fix Typo

---

es/2/1-overview.md
es/2/10-interactingcontracts.md
es/2/11-interactingcontracts2.md
es/2/12-multiplereturns.md
es/2/13-kittygenes.md
es/2/3-msgsender.md
es/2/4-require.md
es/2/7-storage.md
es/3/02-ownable.md
es/3/03-onlyowner.md
es/3/07-zombiecooldowns2.md
es/3/11-savinggasstorage.md

- [Yes] I did these translations myself and own copyright for them
- [Yes] I didn't use a machine to do these translations
- [Yes] I assign all copyright to Loom Network for these translations

It Just fixs a little (but ugly) typo in the Spanish translation.

---

jp/6/08.md

Fixed the part where the correct answer differs from the sample.

---

en/6/07.md
en/6/08.md
en/6/09.md
es/6/07.md
es/6/08.md
es/6/09.md
fr/6/07.md
fr/6/08.md
fr/6/09.md
jp/6/07.md
jp/6/08.md
jp/6/09.md
pt/6/07-sending-transactions.md
pt/6/08-calling-payable-functions.md
pt/6/09-subscribing-to-events.md
zh/6/07.md
zh/6/08.md
zh/6/09.md

Fixed 'camelCase' and matched Example.

Lesson6 Fix Typos

---

es/1/events.md
es/1/functions2.md
es/1/lessonoverview.md
es/4/battle-03.md
es/5/06-erc721-6.md
es/5/07-erc721-7.md
es/5/11-safemath-3.md
es/5/12-safemath-4.md
es/5/13-comments.md

They call me TypoBuster!

---

en/1/functions.md
es/1/functions.md
fr/1/functions.md
jp/1/functions.md
ko/1/functions.md
no/1/functions.md
pl/1/functions.md
pt/1/functions.md
ru/1/functions.md
th/1/functions.md
tr/1/functions.md
zh/1/functions.md

Matched other chapter

---

pl/1/arrays.md
pl/1/arraysstructs2.md
pl/1/contracts.md
pl/1/datatypes.md
pl/1/events.md
pl/1/functions.md
pl/1/functions2.md
pl/1/functions3.md
pl/1/keccak256.md
pl/1/lessoncomplete.md
pl/1/lessonoverview.md
pl/1/math.md
pl/1/puttingittogether.md
pl/1/structs.md
pl/1/web3js.md

https://github.com/loomnetwork/cryptozombie-lessons/issues/256

Fix polish translation of lesson 1

---

fr/5/09-safemath-1.md

Fix translation error

---

pt/1/keccak256.md

make more easy to understand the lesson in Portuguese

fix translation lesson keccak256

---

pt/3/03-onlyowner.md

Fix translation in Lesson 3 Chapter 3

---

ru/4/battle-09.md

enemyZombie is correct than winZombie

Fix ru lesson 4 chapter 9

---

pt/3/05-timeunits.md

Fix translation PT-BR Lesson 3 Chapter 5

---

pt/3/06-zombiecooldowns.md

Fix translation PT-BR Lesson 3 Chapter 6

---

es/2/10-interactingcontracts.md
es/2/3-msgsender.md
es/2/4-require.md
es/2/6-importfiles.md
es/3/02-ownable.md
es/3/03-onlyowner.md
es/3/08-functionmodifiers.md
es/3/10-savinggasview.md
es/4/battle-01.md
es/4/battle-02.md
es/4/battle-03.md
es/4/battle-04.md
es/4/battle-05.md
es/4/battle-06.md
es/4/battle-07.md
es/4/battle-08.md
es/4/battle-09.md

some spanish language corrections

---

pt/3/02-ownable.md

Fix typo in Lesson 3 Chapter 2

---

en/6/05.md
en/6/07.md

fix-en-lesson6-chapter5

---

sk/3/02-ownable.md
sk/5/01-erc721-1.md
sk/index.json

Updates on translations

---

sk/lander.yml

Fix fk lander file

---

en/index.json
es/index.json
fr/index.json
jp/index.json

Add getReward text for en, es, fr, jp

---

en/1/functions2.md

'desireable' -> desirable
- [ x] I didn't use a machine to do these translations

Fixing spelling of 'desirable'

---

en/6/01.md

Fix grammar in Lesson 6 Ch 1

---

fr/2/9-internalfunctions.md

Fix issue #330

---

en/5/05-erc721-5.md

Was doing the lesson and noticed an extra unnecessary line of code.

removed extra unnecessary line of code

---

es/6/02.md

- [x ] I didn't use a machine to do these translations
- [x ] I assign all copyright to Loom Network for these translations

correction errors in the description corrected

---

en/index.json
en/index.ts
zh/index.json
zh/index.ts

sync index files

---

en/5/05-erc721-5.md

Reverts loomnetwork/cryptozombie-lessons#374
clearly you need this line

Revert "removed extra unnecessary line of code"

---

zh/1/arrays.md

The comment "dynamic Array, we can keep adding to it" was previously left untranslated.
- I did these translations myself and own copyright for them
- I didn't use a machine to do these translations
- I assign all copyright to Loom Network for these translations

Translated the comment in line 56 for the Chinese version. 

---

sk/index.json

corrected a typo in Slovak translations

---

es/2/4-require.md

quick-fix-keccack256

---

es/3/05-timeunits.md
es/3/08-functionmodifiers.md
es/4/battle-01.md
es/4/battle-04.md
es/4/battle-05.md
es/4/battle-06.md
es/4/battle-07.md
es/4/battle-08.md
es/5/03-erc721-3.md
es/5/05-erc721-5.md
es/5/08-erc721-8.md
es/5/09-safemath-1.md
es/5/11-safemath-3.md
es/5/12-safemath-4.md
es/5/13-comments.md
es/6/01.md
es/6/06.md
es/6/08.md
es/6/09.md

fixing indentation for spanish translation

fixing indentation for spanish translation

---

zh/7/04.md

- [ yes] I did these translations myself and own copyright for them
- [yes ] I didn't use a machine to do these translations
- [yes ] I assign all copyright to Loom Network for these translations

A simple spelling mistake

---

pt/1/events.md
pt/1/functions2.md

Fix bug in part1 translation - functions2.md

---

en/3/02-ownable.md

Fixed constructor name

---

en/7/03.md

Fixed small error with solidity version in answer and ZBSerializer.sol

---

ko/7/05.md

Add missing word in chapter 5 of lesson 7 (KO)

---

en/7/03.md
jp/7/03.md
ko/7/03.md
zh/7/03.md

fix default solidity version

---

en/2/8-feedandmultiply2.md

Fix grammar

---

de/3/07-zombiecooldowns2.md
es/3/07-zombiecooldowns2.md
fr/3/07-zombiecooldowns2.md
ko/3/07-zombiecooldowns2.md
no/3/07-zombiecooldowns2.md
pt/3/07-zombiecooldowns2.md
ru/3/07-zombiecooldowns2.md
sk/3/07-zombiecooldowns2.md
th/3/07-zombiecooldowns2.md
zh/3/07-zombiecooldowns2.md

In lessons 3-7, the student is directed to:
```
// 3. Call `triggerCooldown`
```
The correct function name is `_triggerCooldown`. This is the function name that exists in the contract, is mentioned in the instructions, and is expected in the solution.

Correctly describe _triggerCooldown

---

en/1/keccak256.md

Spelling Typo

---

es/6/08.md

- [X ] I did these translations myself and own copyright for them

Fix typos in Lesson 6/Chapter 8 Spanish version

---

es/6/06.md

Fix typo in Lesson 6/Chapter 6 Spanish version

---

es/6/05.md

Fix typos in Lesson 6/Chapter 5 Spanish version

---

es/6/04.md

- [X ] I did these translations myself and own copyright for them

Fix typos in Lesson 6/Chapter 4 Spanish version

---

es/6/03.md

Fix typos in Lesson 6/Chapter 3 Spanish version

---

en/14/10.md
en/14/11.md

- [x ] I did these translations myself and own copyright for them
- [ x] I didn't use a machine to do these translations

Variables Typo in Lesson 14 Chapter 10 and Chapter 11

---

en/10/05.md

Code comments should say "mainnet" rather than "rinkeby".
- [ x] I didn't use a machine to do these translations

Update lesson 10 chapter 5 clarifying comments

---

en/16/08.md

reduce double spaces

---

fr/3/00-overview.md

Fix typos in lesson 6:
- `je ne peut pas` -> `je ne peux pas`
Source : [Verbe pouvoir au présent de l'indicatif](https://www.conjugaisonfrancaise.com/pouvoir.html)

fix typo fr in lesson 3 overview

---

en/14/02.md

Fix: _address should be _oracleInstanceAddress

---

en/18/04.md

Fixed typo lesson 18/4

---

en/11/05.md

fix spacing issue that fails a correct code

---

en/11/04.md

Correct contract name to use pascal case

---

fa/16/05.md

Noticed a small typo for https://cryptozombies.io/en/lesson/16/chapter/5. Seems to be fixed on the EN side but not on the FA

Renames AddOracleEvent -> RemoveOracleEvent

---

pt/5/06-erc721-6.md

Improve translation

---

pt/7/00-overview.md
pt/7/01.md
pt/7/02.md
pt/7/03.md
pt/7/04.md
pt/7/05.md
pt/7/06.md
pt/7/07.md
pt/7/08.md
pt/7/09.md
pt/7/10.md
pt/7/11.md
pt/7/lessoncomplete.md
pt/index.json
pt/index.ts

Lesson 7 translated to Portuguese

---

pt/5/01-erc721-1.md

Improving translate for this lesson.

Improve translation in PT-BR

---

fr/2/4-require.md

Problem translation for french user

---

en/11/09.md

fix chapter reference

---

en/11/02.md

Correct contract name to be pascal case

---

en/17/03.md
en/17/04.md
en/17/05.md
fa/17/03.md
fa/17/04.md
fa/17/05.md

The error message in chapters 3-5 didn't match the same error message in later chapters. Chapter 4's beginning code and the answer had different error messages, even though there is nothing in the chapter about it.
---

Normalize error messages in Lesson 17

---

fr/5/13-comments.md

- [X ] I did these translations myself and own copyright for them
- [X ] I didn't use a machine to do these translations
- [X ] I assign all copyright to Loom Network for these translations

Typo avec -> avant

---

fr/3/07-zombiecooldowns2.md
fr/3/10-savinggasview.md
fr/5/05-erc721-5.md

- [x ] I didn't use a machine to do these translations

French grammar fixes

---

en/5/07-erc721-7.md

Use inclusive language (them instead of him)

---

fr/5/13-comments.md

Translation fix

---

en/15/02.md

fix(lesson-15): fix syntax errors in js code snippet

---

en/18/01.md

fix typos in en/18

---

pt/1/contracts.md

Translating a single line of pragma version tip

PT-BR - Translating a single line of pragma version tip

---

es/2/5-inheritance.md

Add missing accents

---

fr/2/14-wrappingitup.md
fr/2/3-msgsender.md
fr/4/withdraw.md
fr/5/13-comments.md

[FR] Fix several typos

---

en/16/06.md
en/16/07.md

FIX typos in 16-6 and 16-7

---

en/19/08.md

there is a typo  in the answer

fix lesson_19_chapter_8

---

en/16/04.md

Important typo because following existing instructions will not pass the lesson.

Fix L16 Ch4 typo

---

en/19/03.md

fix typo l19-ch3

---

de/6/01.md
en/6/01.md
es/6/01.md
fa/6/01.md
fr/6/01.md
it/6/01.md
jp/6/01.md
ko/6/01.md
pt/6/01-intro-web3.md
sk/6/01.md
th/6/01.md
zh/6/01.md

- [ x] I didn't use a machine to do these translations

Boken link: Update link to minified Web3.js file.

---

en/15/02.md
en/15/03.md
en/15/04.md
en/15/05.md
en/15/06.md
en/15/07.md
en/15/08.md
en/15/09.md
en/15/10.md
en/15/11.md
en/15/12.md

Match answer to instructions for lesson 15 chapter 2, and carry changes through the rest of the lesson.
For reference, the instructions we need to match are on line 222 of `en/15/02.md`.
The other option is to change the instructions, but I believe this is better because in real life you would leave in the `return` if you planned to write code below it later, as the lesson says.

Match answer to instructions, lesson 15

---

en/19/07.md

Fix typos in lesson 19 chapter 7

---

es/4/battle-01.md
es/4/battle-04.md
es/4/battle-05.md
es/4/battle-06.md
es/4/battle-07.md
es/4/battle-08.md
es/4/battle-09.md
es/5/01-erc721-1.md
es/5/02-erc721-2.md
es/5/03-erc721-3.md
es/5/04-erc721-4.md
es/5/05-erc721-5.md
es/5/06-erc721-6.md
es/5/07-erc721-7.md
es/5/08-erc721-8.md
es/5/09-safemath-1.md
es/5/10-safemath-2.md
es/5/11-safemath-3.md
es/5/12-safemath-4.md
es/5/13-comments.md
es/6/01.md
es/6/02.md
es/6/03.md
es/6/04.md
es/6/05.md
es/6/06.md
es/6/07.md
es/6/08.md
es/6/09.md

Changed "Póngalo a prueba" to "Vamos a probarlo"
as translated in previous lessons.
```bash
for file in $(grep -lRe 'Póngalo'); do sed -i 's/Póngalo a prueba/Vamos a probarlo/' $file; done
```

Unify translations of "Put it to the test"

---

es/3/02-ownable.md

Lesson 4 is already finished, but the spanish version suggests is not.
The statement does not appear in the english version.

Remove mention of unfinished lesson 4

---

fr/1/events.md

[FR] fix javascript typo

---

fr/index.json

English text translation and spelling mistakes for French translation

---

en/19/08.md
en/19/09.md
en/19/10.md
en/19/11.md

fix typos, update VRF Coordinator address (Rinkeby)

---

ko/6/03.md
ko/6/06.md
ko/6/07.md

[KO] Fix Translated in korean

---

ko/6/07.md

[KO] Fix Translated in lesson 6 chapter 7

---

en/5/13-comments.md

Fix spelling of "transferring" in en/5/13.

---

en/16/06.md

Fix typo in lesson 16 chapter 6, Issue #491

---

en/6/03.md
fa/6/03.md

Fix typo in lesson 6 chapter 3
Fixes https://github.com/loomnetwork/cryptozombie-lessons/issues/213

Fix typo in lesson 6 chapter 3

---

en/6/04.md
es/6/04.md
fr/6/04.md
jp/6/04.md
ko/6/04.md
pt/6/04-calling-contract-functions.md
zh/6/04.md

Since we use semicolons in previous chapters it was pretty confusing when there was none in this lesson. I used a good 2 minutes to understand why my code did not pass. 
This pr will add ; to the relevant lines of the given code and the answer code, in all languages.
_On a side note: My team and I really enjoyed your cryptozombies lessons. Thank you so much!_

Fix missing ; in Lesson 6 chapter 4

---

en/19/10.md

Remove additional 'the' en/19/10.md

---

fr/2/4-require.md

[FR] Fix the meaning of the sentence

---

en/1/functions.md

Strings are not pass by reference in solidity

---

en/17/07.md

Fixing the number of parameters in the description of the function called getFee

Fix: The number of parameters

---

en/16/06.md

Add a missing 'to' in a sentence. en/16/06

---

en/19/07.md

Fix typo in lesson 19 chapter 11

---

jp/2/12-multiplereturns.md

[JP] fix mistranslation in Chapter2-12

---

es/1/lessonoverview.md

Fix the first two digits map to the zombie's head in spanish translation

---

en/lander.yml
es/lander.yml
fa/lander.yml
fr/lander.yml
it/lander.yml
jp/lander.yml
ko/lander.yml
no/lander.yml
pl/lander.yml
pt/lander.yml
ru/lander.yml
sk/lander.yml
th/lander.yml
tr/lander.yml
zh/lander.yml

- replace every languages translation keys with new lander design
- FR is  generated from google translation
- other languages are same as English

replace lander translation with new design

---

en/19/07.md

Removing extra 'the' on lesson 19 chapter 7

---

fr/2/2-mappings.md

[FR] fix typo

---

en/3/11-savinggasstorage.md

FIX: change `however` -> `how` in lesson 11 chapter 3

---

jp/index.json

[JP] Add missing part of chapter

---

fr/3/10-savinggasview.md
fr/index.json

Fix typo french

---

ru/2/7-storage.md

Fix typo in comments in 7-storage.md

---

en/14/03.md

Clarify that functions belong to interfaces

---

en/18/05.md
en/26/06.md
en/27/01.md

chore: remove repeat words

---

en/5/14-wrappingitup.md

Lesson "ERC721 & Crypto-Collectibles", chapter 14 mentioned "In the next 2 lessons" even though the only lesson after that is "App Front-ends & Web3.js". ✌🏼

Update 14-wrappingitup.md (Grammar Fix Request)

---

en/1/arraysstructs2.md
en/1/events.md
en/1/web3js.md
en/10/05.md
en/10/08.md
en/11/03.md
en/11/04.md
en/11/lessoncomplete.md

Rectify typographical inaccuracies
This PR addresses several typographical errors across various files in the project. The changes improve readability and maintain the professional standard of the documentation and code comments.
Justification
Typographical errors, while minor, can detract from the overall quality of the project. Correcting these errors ensures clarity and professionalism, making the project more accessible and understandable for current and future contributors.

Docs improvements

---

es/2/11-interactingcontracts2.md
es/2/4-require.md
es/3/02-ownable.md

[ES] Update various md translations & types

---

zh/lander.yml

This pull request contains changes to improve clarity, correctness and structure.

fix: typos in documentation files

---

fr/lander.yml

missing french translation
