CryptozombiesHQ/cryptozombie-lessons

- en/2/11-interactingcontracts2.md
- jp/2/11-interactingcontracts2.md
- pt/2/11-interactingcontracts2.md
- zh/2/11-interactingcontracts2.md
Added `;` at the end of the lines in Lesson 2 Chapter 11, which is due to Solidity syntax.
Here is where semicolon was missing:
> Not using `;` at the end of the line in example was confusing people

- en/5/09-safemath-1.md
- en/5/10-safemath-2.md
- en/5/11-safemath-3.md
- en/5/12-safemath-4.md
- en/5/13-comments.md
Fixed typo in English version of lesson 5 where in safemath.sol, 'subtracts' was spelled 'substracts' in a comment.
> Fixed 'Subtracts' typo in Lesson 5 EN

- jp/3/08-functionmodifiers.md
[In this page](https://cryptozombies.io/jp/lesson/3/chapter/8), I correct the representation `よりも大きい` (only means "greater than"), to `以上である` (means "greater than or equal").
> fix modules in japanese ver. of lesson3 chapter8

- en/5/03-erc721-3.md
it says
contract ZombieOwnership is ZombieAttack
it should say
contract ZombieOwnership is ZombieBattle
> correction

- en/5/02-erc721-2.md
it says "contract ZombieOwnership is ZombieAttack"
it should be  "contract ZombieOwnership is ZombieBattle"
> error in line 16

- en/5/01-erc721-1.md
- en/5/02-erc721-2.md
- en/5/03-erc721-3.md
- en/5/04-erc721-4.md
- en/5/05-erc721-5.md
- en/5/06-erc721-6.md
- en/5/07-erc721-7.md
- en/5/08-erc721-8.md
- en/5/09-safemath-1.md
- en/5/10-safemath-2.md
- en/5/11-safemath-3.md
- en/5/12-safemath-4.md
- en/5/13-comments.md
`ZombieAttack` and `ZombieBattle` are actually the same contract, answer code and instructions refer to `ZombieAttack`, the file the contract lives in is named `zombieattack.sol`, so `ZombieAttack` should be used everywhere.
> Fix L5 ZombieAttack / ZombieBattle contract references

- en/6/06.md
For some reason `head` variable is referenced as `i` right after it has been declared
> `head` variable name instead of `i`

- fr/2/3-msgsender.md
Line 113 : n'importe qui pourrait appelé -> n'importe qui pourrait appeler
Line 115 : Utiliser `msg,sender` -> Utiliser `msg.sender`
> Just some French translations typos

- jp/5/13-comments.md
翻訳の修正ではなくコードのバグです。
答えのコード中の2行の末尾に ; がなく、エディター側のコードには ; があるため、ユーザーはこの ; 2つを削除しないとテストにパス出来ません。
> Fix a bug in the JP version of lesson 5 chapter 13

- jp/1/functions2.md
'コントラクト' means contruct in English.
Also, '関数' means function in English.
I corrected from 'createZombieコントラクト' to 'createZombie関数'.
> fix: JP translation lesson1 chapter9

- en/3/05-timeunits.md
When perusing the solidity docs, I noticed a slight discrepancy between the definition presented in the lesson. From the [docs](https://solidity.readthedocs.io/en/latest/miscellaneous.html#pitfalls):
"`now` (`uint`): current block timestamp (alias for `block.timestamp`)"
> update `now` description in Time lesson

- en/3/03-onlyowner.md
Replaced unknown method name `likeABoss` with `renounceOwnership`.
The other suitable method name here would be `transferOwnership`
> Fix incorrect method name in Chapter 3: onlyOwner Function Modifier

- en/9/06-erc721x.md
- en/9/07-erc721x.md
- en/9/08-erc721x.md
- en/9/09-erc721x.md
- en/9/10-erc721x.md
- jp/9/06-erc721x.md
- jp/9/07-erc721x.md
- jp/9/08-erc721x.md
- jp/9/09-erc721x.md
- jp/9/10-erc721x.md
- ko/9/06-erc721x.md
- ko/9/07-erc721x.md
- ko/9/08-erc721x.md
- ko/9/09-erc721x.md
- ko/9/10-erc721x.md
- zh/9/06-erc721x.md
- zh/9/07-erc721x.md
- zh/9/08-erc721x.md
- zh/9/09-erc721x.md
- zh/9/10-erc721x.md
In the CryptoZombie Lesson 9, the contract `ZombieCard.sol`, we have declared a `mapping` to store the total supply:
```
mapping(uint => uint) internal tokenIdToIndividualSupply;
```
and a function to view this supply:
```
function individualSupply(uint _tokenId) public view returns (uint);
```
However, in the function `awardToken(uint _tokenId, address _to, uint _amount)`, the second line is:
```
if (individualSupply[_tokenId] > 0)
```
which is wrong. `individualSupply` is the function name not the mapping name. The correct way is:
```
if (individualSupply(_tokenId) > 0)
```
> mix a function name and mapping name (individualSupply) in Lesson 9

- jp/2/9-internalfunctions.md
Hi, thanks for creating and maintaining these tutorials! This PR corrects a typos. とちら should be どちら.
> correct typos とちら => どちら

- de/1/keccak256.md
- en/1/keccak256.md
- no/1/keccak256.md
Hi, thanks for creating and maintaining these tutorials! This PR corrects a spelling error. hexidecimal should be hexadecimal.
> spellcheck hexidecimal -> hexadecimal

- en/12/06.md
Fix typos in lesson 6:
- `Probalistic finality` -> `Probabilistic finality`
- `libra&` -> `libra%`
> Fix typos in lesson 6

- jp/6/08.md
Fix small typo. (`Power`:  "パー" -> "パワー")
> Fix small JP typo

- en/3/07-zombiecooldowns2.md
The function's name is _triggerCooldown yet it is referenced in a comment as triggerCooldown
> Fix function name in comment

- en/16/05.md
- en/16/lessoncomplete.md
Current (Instruction in Lesson 16, Chapter 5 states to fire AddOracleEvent instead of RemoveOracleEvent):
Changes:
[x] Fix typos
> Update instruction to fire RemoveOracleEvent instead of AddOracleEvent

- en/14/02.md
- en/14/10.md
Aligning the variable name passed in the function with what the user is supposed to input.
> aligning variable-name in exercise

- en/3/02-ownable.md
> Replaced old constructor with new constructor syntax

- en/14/09.md
- en/14/10.md
- en/14/11.md
- en/15/01.md
- en/15/02.md
- en/15/03.md
- en/15/04.md
- en/15/05.md
- en/15/06.md
- en/15/07.md
- en/15/08.md
- en/15/09.md
- en/15/10.md
- en/15/11.md
- en/15/12.md
- en/16/01.md
- en/16/02.md
- en/16/03.md
- en/16/04.md
- en/16/05.md
- en/16/06.md
- en/16/07.md
- en/16/08.md
- en/16/09.md
- en/16/10.md
Fixes a small typo in the content and the source examples.
```
CallerContracInterface => CallerContractInterface
```
> Fix typo "CallerContracInterface"

- en/14/10.md
add underscore before each parameters in accordance with the answer.
> add underscore

- en/5/05-erc721-5.md
"paramater"=>"parameter" in Lesson 5 / Chapter 5 in English.
> Typo "paramater" en-5-5

- en/14/11.md
> [easy] Fix typo `CallerContracInterface` -> `CallerContractInterface` in en/14/11.md

- th/6/07.md
- Fixed Thai typos at line 599 (ำvent > event)
- Correctly describe Thai language at line 602 (ใรปริมาณ > ในปริมาณ)
> Update lesson 6 - 07.md (Fixed/Correctly describe Thai language)

- en/16/05.md
At **Advanced Solidity Path: Get In-depth Knowledge - How to Build an Oracle - Part 3 - Chapter 5: Removing an Oracle** 
Localized by the url [https://cryptozombies.io/en/lesson/16/chapter/5](https://cryptozombies.io/en/lesson/16/chapter/5) .
The item 6 in "Put It to the Test" section, the event name should be ~~`AddOracleEvent`~~ `RemoveOracleEvent`
> Fix a typo in chapter 5, lesson 16

- ru/3/12-forloops.md
> Fix typo in ru/3/12-forloops.md

- ru/3/08-functionmodifiers.md
Removed English sentence in Russian locale
> Fix typo in ru/3/8-functionmodifiers.md

- en/5/10-safemath-2.md
- es/5/10-safemath-2.md
- fa/5/10-safemath-2.md
- it/5/10-safemath-2.md
- ru/5/10-safemath-2.md
Turned `zombieApprovals [_tokenId]` into `zombieApprovals[_tokenId]` in all translations for Lesson 5 Chapter 10 (SafeMath part 2)
> Remove an extra space in Lesson 5 Chapter 10

- ko/2/12-multiplereturns.md
`_kittyID` to `_kittyId` at line 160
> Fix typo in ko/2/12-multiplereturns.md

- en/10/10.md
- fa/10/10.md
Removed an orphan return statement left from previous lessons on creating the Loom provider for Truffle.
> fix: remove early return statement

- es/2/2-mappings.md
"financial" is not a spanish adjective, the right one is "financiera"
See https://dle.rae.es/financial and https://dle.rae.es/financiero
> Change "financial" to "financiera"

- en/17/11.md
Localized by the url [https://cryptozombies.io/en/lesson/17/chapter/11](https://cryptozombies.io/en/lesson/17/chapter/11).
At the end of the page the variable `bobZkSync` doesn't match the answer validation which is `bobZkSyncWallet`
> Fix bobZkSyncWallet to match answer validation

- en/1/keccak256.md
Changed it from "hexidecimal" to "hexadecimal"
> Corrected spelling of "hexadecimal"

- es/2/2-mappings.md
- `dirección` is not the variable, so `address` is used instead between parenthesis next to the spanish word.
- In the english version, the phrase "ver los usuarios basados en ese userId" ends with "based on userId". It refers to any possible userId, not anyone in particular, which it's implicitly stated in the spanish version. So "un" is preferred over "ese" in this case.
- The sense of the english word "key" is incorrectly interpreted in spanish as "device that opens a lock" or "winding tool for a mechanism". "Clave" is preferred over "llave" in that case. See https://www.wordreference.com/es/translation.asp?tranword=key
> Update 2-mappings.md with several changes

- en/3/02-ownable.md
-> constructors don't have a name
> Enhancement: remove invalid part of sentence

- en/10/10.md
**Summary**
For Lesson 10 (Deploying Dapps with Truffle) Chapter 10 (Deploy to Basechain) (en), there was one line of code dangling from a previous chapter. 
No new translations.
> Fix: remove one line of code from previous lesson

- en/10/05.md
Replace `var` with `const` - updated syntax and the solutions expects const as well.
> Update en/10/05.md - replace var with const

- en/14/03.md
Line 82:
2. Next, you must import the contents of the `./FastFoodInterface.sol` file into the `PrepareLaunch` contract.
REPLACE `PrepareLaunch` with `PrepareLunch`
> Changed typo PrepareLaunch to PrepareLunch

- en/11/03.md
The comment refers to a third point in the requirements and asks to `"replace the first parameter"`, however there are only two requirement points.
> update(11/03.md): Fix JS comment to match the reqs

- en/17/01.md
The answer and hint just use 'ethers' whilst the help said 'ethersjs'
> Remove 'js' from 'ethersjs' in help command

- en/4/payable.md
Removed the word "both" as it implies only 2 arguments or parts, but this sentence has 3: money, data and contract itself. Also added em/italics to "and" in addition to bold text because italics imply an emphasized tone of inflection - felt more appropriate than bold, only.
- [x ] I did these translations myself and own copyright for them
- [x ] I didn't use a machine to do these translations
- [x ] I assign all copyright to Loom Network for these translations
> English 'syntax' update to help the sentence make more sense.

- en/14/04.md
There were two instances where OpenZeppelin was misspelled, so I corrected them.
> Fix misspellings of OpenZeppelin

- jp/index.json
I found a duplicate object key and fixed it.
There were two `getReward` key in `lessonMenu` in `jp/index.json`
> [JP] Fix duplicate object key "lessonMenu.getReward"

- jp/6/07.md
Make a copy of `createRandomZombie` right below it, but make the following changes:
- As is: そのすぐ下に `createRandomZombie` のコピーを作成するが、以下の変更をするように:
The above Japanese text did not make sense to me, so I translated it as follows
- To be: `createRandomZombie`のコピーをその真下に作成せよ。ただし、以下の変更をするように:
> [JP] lesson6 chapter7: Translate more natural

- sk/6/02.md
- sk/6/06.md
1. **File:** `/sk/6/06.md`
- Fixed `objekt` to `object` (Line 519)
- Fixed `blok` to `block, bloke` (Line 565)
1. **File:** `/sk/6/02.md`
- Fixed `objekt` to `object` (Line 422)
- EImproved the documentation's clarity and professional tone.
- Corrected small grammatical errors to enhance comprehension.
> Corrected typos

- fr/1/functions2.md
- fr/1/functions3.md
- fr/1/lessonoverview.md
- fr/2/10-interactingcontracts.md
- fr/2/11-interactingcontracts2.md
- fr/2/2-mappings.md
> Fix French language errors

- es/3/12-forloops.md
Fixed error of using word exteremadamente instead of extremely in file es/3/12-forloops.md
Closes: GH-782
> [es] Fix language error in lesson 3.12

- en/5/13-comments.md
There are very minor grammatical errors i came across while reading the content, so i have added the fixes for future.
> Grammatical error correction in content
